--------------------------------------------------------
--  File created - szerda-március-22-2023
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BEFIZETES
--------------------------------------------------------
CREATE TABLE "C##AGZURU"."BEFIZETES" (
  "NEV" VARCHAR2(64 BYTE), 
  "OSSZEG" NUMBER(8, 0), 
  "NEPTUNKOD" VARCHAR2(6 BYTE), 
  "HATARIDO" DATE, 
  "BEFIZETVE" NUMBER
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table FELVETEL
--------------------------------------------------------
CREATE TABLE "C##AGZURU"."FELVETEL" (
  "NEPTUNKOD" VARCHAR2(6 BYTE), 
  "KURZUSKOD" VARCHAR2(10 BYTE), 
  "HANYADIK" NUMBER(1, 0), 
  "JEGY" NUMBER(1, 0)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table FORUM
--------------------------------------------------------
CREATE TABLE "C##AGZURU"."FORUM" (
  "ID" NUMBER(4, 0), 
  "NEPTUNKOD" VARCHAR2(6 BYTE), 
  "UZENET" VARCHAR2(512 BYTE), 
  "IDOPONT" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table HALLGATO
--------------------------------------------------------
CREATE TABLE "C##AGZURU"."HALLGATO" (
  "NEPTUNKOD" VARCHAR2(6 BYTE), 
  "SZAKKOD" VARCHAR2(10 BYTE), 
  "NEV" VARCHAR2(20 BYTE), 
  "JELSZO" VARCHAR2(20 BYTE)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table KURZUS
--------------------------------------------------------
CREATE TABLE "C##AGZURU"."KURZUS" (
  "KURZUSKOD" VARCHAR2(10 BYTE), 
  "KURZUSNEV" VARCHAR2(50 BYTE), 
  "IDOPONT" VARCHAR2(20 BYTE), 
  "OKTATO" VARCHAR2(10 BYTE), 
  "AJANLOTTFELEV" NUMBER(2, 0), 
  "TEREMSZAM" NUMBER(3, 0)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table NEPTUNREFERENS
--------------------------------------------------------
CREATE TABLE "C##AGZURU"."NEPTUNREFERENS" (
  "NEPTUNKOD" VARCHAR2(6 BYTE), 
  "NEV" VARCHAR2(20 BYTE), 
  "JELSZO" VARCHAR2(20 BYTE)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table OKTATJA
--------------------------------------------------------
CREATE TABLE "C##AGZURU"."OKTATJA" (
  "NEPTUNKOD" VARCHAR2(6 BYTE), 
  "KURZUSKOD" VARCHAR2(10 BYTE)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table OKTATO
--------------------------------------------------------
CREATE TABLE "C##AGZURU"."OKTATO" (
  "NEPTUNKOD" VARCHAR2(6 BYTE), 
  "NEV" VARCHAR2(20 BYTE), 
  "JELSZO" VARCHAR2(20 BYTE)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table SZAK
--------------------------------------------------------
CREATE TABLE "C##AGZURU"."SZAK" (
  "SZAKKOD" VARCHAR2(10 BYTE), 
  "SZAKNEV" VARCHAR2(128 BYTE)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table TEREM
--------------------------------------------------------
CREATE TABLE "C##AGZURU"."TEREM" (
  "TEREMSZAM" NUMBER(3, 0), 
  "BEFOGADOKEPESSEG" NUMBER(2, 0)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";
REM INSERTING into C ##AGZURU.BEFIZETES
SET 
  DEFINE OFF;
Insert into C ##AGZURU.BEFIZETES (NEV,OSSZEG,NEPTUNKOD,HATARIDO,BEFIZETVE) values ('2019/2020-Március','9320','WNHA8U',to_date('20-MÁRC. -15','RR-MON-DD'),'0');
Insert into C ##AGZURU.BEFIZETES (NEV,OSSZEG,NEPTUNKOD,HATARIDO,BEFIZETVE) values ('2019/2020-Március','9320','W0DVIE',to_date('20-MÁRC. -15','RR-MON-DD'),'0');
Insert into C ##AGZURU.BEFIZETES (NEV,OSSZEG,NEPTUNKOD,HATARIDO,BEFIZETVE) values ('2019/2020-Március','9320','EJJRS9',to_date('20-MÁRC. -15','RR-MON-DD'),'0');
Insert into C ##AGZURU.BEFIZETES (NEV,OSSZEG,NEPTUNKOD,HATARIDO,BEFIZETVE) values ('2019/2020-Március','9320','D526DN',to_date('20-MÁRC. -15','RR-MON-DD'),'0');
Insert into C ##AGZURU.BEFIZETES (NEV,OSSZEG,NEPTUNKOD,HATARIDO,BEFIZETVE) values ('2019/2020-Március','9320','LTPHSA',to_date('20-MÁRC. -15','RR-MON-DD'),'0');
Insert into C ##AGZURU.BEFIZETES (NEV,OSSZEG,NEPTUNKOD,HATARIDO,BEFIZETVE) values ('2019/2020-Március','9320','2FLH89',to_date('20-MÁRC. -15','RR-MON-DD'),'0');
Insert into C ##AGZURU.BEFIZETES (NEV,OSSZEG,NEPTUNKOD,HATARIDO,BEFIZETVE) values ('2019/2020-Március','9320','5CSN0Y',to_date('20-MÁRC. -15','RR-MON-DD'),'0');
Insert into C ##AGZURU.BEFIZETES (NEV,OSSZEG,NEPTUNKOD,HATARIDO,BEFIZETVE) values ('2019/2020-Március','9320','BB72TP',to_date('20-MÁRC. -15','RR-MON-DD'),'0');
Insert into C ##AGZURU.BEFIZETES (NEV,OSSZEG,NEPTUNKOD,HATARIDO,BEFIZETVE) values ('2019/2020-Március','9320','5WE0FH',to_date('20-MÁRC. -15','RR-MON-DD'),'0');
Insert into C ##AGZURU.BEFIZETES (NEV,OSSZEG,NEPTUNKOD,HATARIDO,BEFIZETVE) values ('2019/2020-Március','9320','KYOM2X',to_date('20-MÁRC. -15','RR-MON-DD'),'0');
REM INSERTING into C ##AGZURU.FELVETEL
SET 
  DEFINE OFF;
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('WNHA8U','IB407','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('WNHA8U','GBN509','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('WNHA8U','10B101','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('WNHA8U','GKBN04S','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('WNHA8U','IBK203','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('WNHA8U','IB402','1','4');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('WNHA8U','IB104','1','1');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('WNHA8U','IB162E','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('W0DVIE','IB407','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('W0DVIE','MBNXK262','1','4');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('W0DVIE','GKBN04S','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('W0DVIE','IB162E','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('W0DVIE','10B101','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('W0DVIE','GBN509','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('W0DVIE','IB402','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('W0DVIE','XT0011','1','4');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('EJJRS9','MBNXK262','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('EJJRS9','IB676','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('EJJRS9','IB407','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('EJJRS9','IB104','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('EJJRS9','XT0011','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('EJJRS9','IB204','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('EJJRS9','GKBN04S','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('EJJRS9','IBK203','1','4');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('D526DN','IB676','1','4');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('D526DN','XT0011','1','4');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('D526DN','GKBN04S','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('D526DN','IB104','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('D526DN','IB407','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('D526DN','GBN509','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('D526DN','10B101','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('D526DN','IB402','1','4');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('LTPHSA','IB162E','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('LTPHSA','10B101','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('LTPHSA','MBNXK262','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('LTPHSA','IB402','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('LTPHSA','IB407','1','1');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('LTPHSA','IB676','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('LTPHSA','GKBN04S','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('LTPHSA','XT0011','1','1');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('2FLH89','IB676','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('2FLH89','XT0011','1','1');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('2FLH89','GKBN04S','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('2FLH89','IB162E','1','1');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('2FLH89','GBN509','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('2FLH89','GKBN04S','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('2FLH89','IB104','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('2FLH89','IB407','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5CSN0Y','IBK203','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5CSN0Y','10B101','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5CSN0Y','IB104','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5CSN0Y','IB676','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5CSN0Y','XT0011','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5CSN0Y','GKBN04S','1','4');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5CSN0Y','IB402','1','4');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5CSN0Y','GBN509','1','4');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('BB72TP','MBNXK262','1','4');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('BB72TP','10B101','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('BB72TP','IB407','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('BB72TP','IB162E','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('BB72TP','IB204','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('BB72TP','XT0011','1','4');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('BB72TP','GKBN04S','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('BB72TP','IB402','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5WE0FH','IB402','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5WE0FH','IB407','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5WE0FH','GKBN04S','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5WE0FH','IB104','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5WE0FH','GBN509','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5WE0FH','10B101','1','3');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5WE0FH','XT0011','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('5WE0FH','IBK203','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('KYOM2X','IB162E','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('KYOM2X','IBK203','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('KYOM2X','IB407','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('KYOM2X','GBN509','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('KYOM2X','IB204','1','2');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('KYOM2X','10B101','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('KYOM2X','IB104','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('KYOM2X','IB162E','1','5');
Insert into C ##AGZURU.FELVETEL (NEPTUNKOD,KURZUSKOD,HANYADIK,JEGY) values ('KYOM2X','GKBN04S','1','5');
REM INSERTING into C ##AGZURU.FORUM
SET 
  DEFINE OFF;
Insert into C ##AGZURU.FORUM (ID,NEPTUNKOD,UZENET,IDOPONT) values ('1','UFFBHC','Tisztelt hallgatók! Koronavírus van, nem kelliskolába jönni! juhu',to_timestamp('21-MÁJ.  -09 18.40.53,962616000','RR-MON-DD HH24.MI.SSXFF'));
Insert into C ##AGZURU.FORUM (ID,NEPTUNKOD,UZENET,IDOPONT) values ('2','UQ1XST','Tisztelt hallgatók! Tessék menni vért adni',to_timestamp('21-MÁJ.  -09 18.40.53,970363000','RR-MON-DD HH24.MI.SSXFF'));
Insert into C ##AGZURU.FORUM (ID,NEPTUNKOD,UZENET,IDOPONT) values ('3','SV3NJC','Tisztelt hallgatók! Töltsék ki ezt meg azt, hogy az egyetemnek jó legyen',to_timestamp('21-MÁJ.  -09 18.40.53,975501000','RR-MON-DD HH24.MI.SSXFF'));
Insert into C ##AGZURU.FORUM (ID,NEPTUNKOD,UZENET,IDOPONT) values ('4','PMEQQS','Tisztelt hallgatók! Az dékáni szünet lesz az év hátralevő részébe',to_timestamp('21-MÁJ.  -09 18.40.53,980849000','RR-MON-DD HH24.MI.SSXFF'));
Insert into C ##AGZURU.FORUM (ID,NEPTUNKOD,UZENET,IDOPONT) values ('5','RU4ZI3','Tisztelt hallgatók! Vizsgaidőszak van, mindenki meg lesz buktatva',to_timestamp('21-MÁJ.  -09 18.40.53,985561000','RR-MON-DD HH24.MI.SSXFF'));
Insert into C ##AGZURU.FORUM (ID,NEPTUNKOD,UZENET,IDOPONT) values ('6','XAJ221','Tisztelt hallgatók! Boldog új évet, mindenki mindenből öts lett',to_timestamp('21-MÁJ.  -09 18.40.53,990307000','RR-MON-DD HH24.MI.SSXFF'));
Insert into C ##AGZURU.FORUM (ID,NEPTUNKOD,UZENET,IDOPONT) values ('7','Z5LKZS','Tisztelt hallgatók! A kalkulus még könnyű tantárgynak számít',to_timestamp('21-MÁJ.  -09 18.40.53,997938000','RR-MON-DD HH24.MI.SSXFF'));
REM INSERTING into C ##AGZURU.HALLGATO
SET 
  DEFINE OFF;
Insert into C ##AGZURU.HALLGATO (NEPTUNKOD,SZAKKOD,NEV,JELSZO) values ('WNHA8U','gi_bsc','Takács Vilmos','nRN5mS8HM9');
Insert into C ##AGZURU.HALLGATO (NEPTUNKOD,SZAKKOD,NEV,JELSZO) values ('W0DVIE','gi_bsc','Jakab Zsombor','avQ5PrHN64');
Insert into C ##AGZURU.HALLGATO (NEPTUNKOD,SZAKKOD,NEV,JELSZO) values ('EJJRS9','gi_bsc','Juhász Csaba','b67RMW7fRA');
Insert into C ##AGZURU.HALLGATO (NEPTUNKOD,SZAKKOD,NEV,JELSZO) values ('D526DN','pti_bsc','Papp Márkó','8BtE3DFKi7');
Insert into C ##AGZURU.HALLGATO (NEPTUNKOD,SZAKKOD,NEV,JELSZO) values ('LTPHSA','pti_bsc','Szűts Zalán','Haxo693qMl');
Insert into C ##AGZURU.HALLGATO (NEPTUNKOD,SZAKKOD,NEV,JELSZO) values ('2FLH89','pti_bsc','Gál László','8cRgtb3F5C');
Insert into C ##AGZURU.HALLGATO (NEPTUNKOD,SZAKKOD,NEV,JELSZO) values ('5CSN0Y','mi_bsc','Pintér Áron','Ttr0MdfLoT');
Insert into C ##AGZURU.HALLGATO (NEPTUNKOD,SZAKKOD,NEV,JELSZO) values ('BB72TP','mi_bsc','Fekete Szilárd','tr3wEKAwQ6');
Insert into C ##AGZURU.HALLGATO (NEPTUNKOD,SZAKKOD,NEV,JELSZO) values ('5WE0FH','mi_bsc','Kocsis Norbert','m0fegTBY8n');
Insert into C ##AGZURU.HALLGATO (NEPTUNKOD,SZAKKOD,NEV,JELSZO) values ('KYOM2X','pti_bsc','Vass Laszlo','cYgA5Tplgc');
Insert into C ##AGZURU.HALLGATO (NEPTUNKOD,SZAKKOD,NEV,JELSZO) values ('HH','pti_bsc','C##AGZURUjoee','123');
REM INSERTING into C ##AGZURU.KURZUS
SET 
  DEFINE OFF;
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('IB407','Számítógép_hálózatok','H:10:00-11:00','UFFBHC','1','212');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('GBN509','EU alapismeretek','SZE:12:00-14:00','UQ1XST','1','302');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('IB104','Programozás alapjai','K:08:00-11:00','SV3NJC','1','213');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('10B101','Menedzsment','SZE:16:00-18:00','PMEQQS','1','301');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('IB162E','Számítógép architektúrák','H:12:00-14:00','RU4ZI3','1','214');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('GKBN04S','Mikroökonómia','CS:18:00-20:00','XAJ221','2','300');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('IB204','Programozás I.','SZE:18:00-19:00','96T219','2','222');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('IB402','Operációs rendszerek','K:18:00-20:00','HOWIJ4','2','216');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('IBK203','Operációkutatás','SZ:08:00-10:00','F406UH','2','217');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('MBNXK262','A sztohasztika alapjai','H:16:00-18:00','5UCV7E','2','221');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('IB676','Assembly programozás','K:13:00-14:00','8HBWVY','2','220');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('XT0011','Falmászás','H:10:00-11:00','Z5LKZS','2','225');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('GBN402','EU A','SZE:14:00-15:00','UFFBHC','1','212');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('GHB302','GH H','H:16:00-19:00','SV3NJC','1','213');
Insert into C ##AGZURU.KURZUS (KURZUSKOD,KURZUSNEV,IDOPONT,OKTATO,AJANLOTTFELEV,TEREMSZAM) values ('gdfg','fsdfdsf','fsd','5UCV7E','1','302');
REM INSERTING into C ##AGZURU.NEPTUNREFERENS
SET 
  DEFINE OFF;
Insert into C ##AGZURU.NEPTUNREFERENS (NEPTUNKOD,NEV,JELSZO) values ('EGNQZV','Sípos Bernadett','4m0gVqkZwv');
Insert into C ##AGZURU.NEPTUNREFERENS (NEPTUNKOD,NEV,JELSZO) values ('6ULXZO','Kocsis Flóra','vc6a1n5U86');
Insert into C ##AGZURU.NEPTUNREFERENS (NEPTUNKOD,NEV,JELSZO) values ('NTMRSP','Király Endre','gUJr0o8Nba');
Insert into C ##AGZURU.NEPTUNREFERENS (NEPTUNKOD,NEV,JELSZO) values ('HH','HH','123');
REM INSERTING into C ##AGZURU.OKTATJA
SET 
  DEFINE OFF;
Insert into C ##AGZURU.OKTATJA (NEPTUNKOD,KURZUSKOD) values ('UFFBHC','IB407');
Insert into C ##AGZURU.OKTATJA (NEPTUNKOD,KURZUSKOD) values ('UQ1XST','GBN509');
Insert into C ##AGZURU.OKTATJA (NEPTUNKOD,KURZUSKOD) values ('SV3NJC','IB104');
Insert into C ##AGZURU.OKTATJA (NEPTUNKOD,KURZUSKOD) values ('PMEQQS','10B101');
Insert into C ##AGZURU.OKTATJA (NEPTUNKOD,KURZUSKOD) values ('RU4ZI3','IB162E');
Insert into C ##AGZURU.OKTATJA (NEPTUNKOD,KURZUSKOD) values ('XAJ221','GKBN04S');
Insert into C ##AGZURU.OKTATJA (NEPTUNKOD,KURZUSKOD) values ('96T219','IB204');
Insert into C ##AGZURU.OKTATJA (NEPTUNKOD,KURZUSKOD) values ('HOWIJ4','IB402');
Insert into C ##AGZURU.OKTATJA (NEPTUNKOD,KURZUSKOD) values ('F406UH','IBK203');
Insert into C ##AGZURU.OKTATJA (NEPTUNKOD,KURZUSKOD) values ('5UCV7E','MBNXK262');
Insert into C ##AGZURU.OKTATJA (NEPTUNKOD,KURZUSKOD) values ('8HBWVY','IB676');
Insert into C ##AGZURU.OKTATJA (NEPTUNKOD,KURZUSKOD) values ('Z5LKZS','XT0011');
Insert into C ##AGZURU.OKTATJA (NEPTUNKOD,KURZUSKOD) values ('SV3NJC','GHB302');
REM INSERTING into C ##AGZURU.OKTATO
SET 
  DEFINE OFF;
Insert into C ##AGZURU.OKTATO (NEPTUNKOD,NEV,JELSZO) values ('UFFBHC','Halász Dénes','0S1mE4CDu1');
Insert into C ##AGZURU.OKTATO (NEPTUNKOD,NEV,JELSZO) values ('UQ1XST','Bogdán Dominik','7WL4sTla2e');
Insert into C ##AGZURU.OKTATO (NEPTUNKOD,NEV,JELSZO) values ('SV3NJC','Orsós Sándor','zzt3ZlCjMs');
Insert into C ##AGZURU.OKTATO (NEPTUNKOD,NEV,JELSZO) values ('PMEQQS','Borbély Károly','Si8CifQ54M');
Insert into C ##AGZURU.OKTATO (NEPTUNKOD,NEV,JELSZO) values ('RU4ZI3','Csonka Máté','rUbXz90Wy8');
Insert into C ##AGZURU.OKTATO (NEPTUNKOD,NEV,JELSZO) values ('XAJ221','Vörös Botond','8PG4miHeFJ');
Insert into C ##AGZURU.OKTATO (NEPTUNKOD,NEV,JELSZO) values ('96T219','Magyar Gergő','Dyr3H8K11T');
Insert into C ##AGZURU.OKTATO (NEPTUNKOD,NEV,JELSZO) values ('HOWIJ4','Pataki Sándor','bSEIURt2cV');
Insert into C ##AGZURU.OKTATO (NEPTUNKOD,NEV,JELSZO) values ('F406UH','Fehér Henrik','S6PORuRXcR');
Insert into C ##AGZURU.OKTATO (NEPTUNKOD,NEV,JELSZO) values ('5UCV7E','Bodnár Flórián','YE6l0ot0CD');
Insert into C ##AGZURU.OKTATO (NEPTUNKOD,NEV,JELSZO) values ('8HBWVY','Gál Krisztina','QqDXC87FyG');
Insert into C ##AGZURU.OKTATO (NEPTUNKOD,NEV,JELSZO) values ('Z5LKZS','Csatár Ildikó','QRwJ1fixNe');
REM INSERTING into C ##AGZURU.SZAK
SET 
  DEFINE OFF;
Insert into C ##AGZURU.SZAK (SZAKKOD,SZAKNEV) values ('gi_bsc','Gazdaságinformatikus Bsc');
Insert into C ##AGZURU.SZAK (SZAKKOD,SZAKNEV) values ('pti_bsc','Programtervrző informatikus Bsc');
Insert into C ##AGZURU.SZAK (SZAKKOD,SZAKNEV) values ('mi_bsc','Mérnökinformatikus Bsc');
REM INSERTING into C ##AGZURU.TEREM
SET 
  DEFINE OFF;
Insert into C ##AGZURU.TEREM (TEREMSZAM,BEFOGADOKEPESSEG) values ('212','30');
Insert into C ##AGZURU.TEREM (TEREMSZAM,BEFOGADOKEPESSEG) values ('213','30');
Insert into C ##AGZURU.TEREM (TEREMSZAM,BEFOGADOKEPESSEG) values ('214','25');
Insert into C ##AGZURU.TEREM (TEREMSZAM,BEFOGADOKEPESSEG) values ('216','30');
Insert into C ##AGZURU.TEREM (TEREMSZAM,BEFOGADOKEPESSEG) values ('217','60');
Insert into C ##AGZURU.TEREM (TEREMSZAM,BEFOGADOKEPESSEG) values ('220','30');
Insert into C ##AGZURU.TEREM (TEREMSZAM,BEFOGADOKEPESSEG) values ('221','35');
Insert into C ##AGZURU.TEREM (TEREMSZAM,BEFOGADOKEPESSEG) values ('222','50');
Insert into C ##AGZURU.TEREM (TEREMSZAM,BEFOGADOKEPESSEG) values ('225','25');
Insert into C ##AGZURU.TEREM (TEREMSZAM,BEFOGADOKEPESSEG) values ('300','30');
Insert into C ##AGZURU.TEREM (TEREMSZAM,BEFOGADOKEPESSEG) values ('301','30');
Insert into C ##AGZURU.TEREM (TEREMSZAM,BEFOGADOKEPESSEG) values ('302','35');
Insert into C ##AGZURU.TEREM (TEREMSZAM,BEFOGADOKEPESSEG) values ('12','12');
--------------------------------------------------------
--  Constraints for Table TEREM
--------------------------------------------------------
ALTER TABLE 
  "C##AGZURU"."TEREM" 
ADD 
  PRIMARY KEY ("TEREMSZAM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "C##AGZURU"."TEREM" MODIFY (
    "BEFOGADOKEPESSEG" NOT NULL ENABLE
  );
ALTER TABLE 
  "C##AGZURU"."TEREM" MODIFY ("TEREMSZAM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HALLGATO
--------------------------------------------------------
ALTER TABLE 
  "C##AGZURU"."HALLGATO" 
ADD 
  PRIMARY KEY ("NEPTUNKOD") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "C##AGZURU"."HALLGATO" MODIFY ("JELSZO" NOT NULL ENABLE);
ALTER TABLE 
  "C##AGZURU"."HALLGATO" MODIFY ("NEV" NOT NULL ENABLE);
ALTER TABLE 
  "C##AGZURU"."HALLGATO" MODIFY ("SZAKKOD" NOT NULL ENABLE);
ALTER TABLE 
  "C##AGZURU"."HALLGATO" MODIFY ("NEPTUNKOD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OKTATO
--------------------------------------------------------
ALTER TABLE 
  "C##AGZURU"."OKTATO" 
ADD 
  PRIMARY KEY ("NEPTUNKOD") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "C##AGZURU"."OKTATO" MODIFY ("JELSZO" NOT NULL ENABLE);
ALTER TABLE 
  "C##AGZURU"."OKTATO" MODIFY ("NEV" NOT NULL ENABLE);
ALTER TABLE 
  "C##AGZURU"."OKTATO" MODIFY ("NEPTUNKOD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NEPTUNREFERENS
--------------------------------------------------------
ALTER TABLE 
  "C##AGZURU"."NEPTUNREFERENS" 
ADD 
  PRIMARY KEY ("NEPTUNKOD") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "C##AGZURU"."NEPTUNREFERENS" MODIFY ("JELSZO" NOT NULL ENABLE);
ALTER TABLE 
  "C##AGZURU"."NEPTUNREFERENS" MODIFY ("NEV" NOT NULL ENABLE);
ALTER TABLE 
  "C##AGZURU"."NEPTUNREFERENS" MODIFY ("NEPTUNKOD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KURZUS
--------------------------------------------------------
ALTER TABLE 
  "C##AGZURU"."KURZUS" 
ADD 
  PRIMARY KEY ("KURZUSKOD") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "C##AGZURU"."KURZUS" MODIFY ("KURZUSKOD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SZAK
--------------------------------------------------------
ALTER TABLE 
  "C##AGZURU"."SZAK" 
ADD 
  PRIMARY KEY ("SZAKKOD") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "C##AGZURU"."SZAK" MODIFY ("SZAKKOD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FORUM
--------------------------------------------------------
ALTER TABLE 
  "C##AGZURU"."FORUM" 
ADD 
  PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "C##AGZURU"."FORUM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BEFIZETES
--------------------------------------------------------
ALTER TABLE 
  "C##AGZURU"."BEFIZETES" 
ADD 
  FOREIGN KEY ("NEPTUNKOD") REFERENCES "C##AGZURU"."HALLGATO" ("NEPTUNKOD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FELVETEL
--------------------------------------------------------
ALTER TABLE 
  "C##AGZURU"."FELVETEL" 
ADD 
  FOREIGN KEY ("NEPTUNKOD") REFERENCES "C##AGZURU"."HALLGATO" ("NEPTUNKOD") ENABLE;
ALTER TABLE 
  "C##AGZURU"."FELVETEL" 
ADD 
  FOREIGN KEY ("KURZUSKOD") REFERENCES "C##AGZURU"."KURZUS" ("KURZUSKOD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FORUM
--------------------------------------------------------
ALTER TABLE 
  "C##AGZURU"."FORUM" 
ADD 
  FOREIGN KEY ("NEPTUNKOD") REFERENCES "C##AGZURU"."OKTATO" ("NEPTUNKOD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HALLGATO
--------------------------------------------------------
ALTER TABLE 
  "C##AGZURU"."HALLGATO" 
ADD 
  FOREIGN KEY ("SZAKKOD") REFERENCES "C##AGZURU"."SZAK" ("SZAKKOD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KURZUS
--------------------------------------------------------
ALTER TABLE 
  "C##AGZURU"."KURZUS" 
ADD 
  FOREIGN KEY ("OKTATO") REFERENCES "C##AGZURU"."OKTATO" ("NEPTUNKOD") ENABLE;
ALTER TABLE 
  "C##AGZURU"."KURZUS" 
ADD 
  FOREIGN KEY ("TEREMSZAM") REFERENCES "C##AGZURU"."TEREM" ("TEREMSZAM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OKTATJA
--------------------------------------------------------
ALTER TABLE 
  "C##AGZURU"."OKTATJA" 
ADD 
  FOREIGN KEY ("NEPTUNKOD") REFERENCES "C##AGZURU"."OKTATO" ("NEPTUNKOD") ENABLE;
ALTER TABLE 
  "C##AGZURU"."OKTATJA" 
ADD 
  FOREIGN KEY ("KURZUSKOD") REFERENCES "C##AGZURU"."KURZUS" ("KURZUSKOD") ENABLE;
